DROP DATABASE ViaTech;
CREATE DATABASE viatech;
USE viatech;

CREATE TABLE empresa(
idEmpresa INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
nomeFantasia VARCHAR(100) NOT NULL,
CNPJ CHAR(14) NOT NULL,
telefone CHAR(11) NOT NULL,
email VARCHAR(100) NOT NULL,
senha VARCHAR(100) NOT NULL
);

CREATE TABLE funcionario(
idFuncionario INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
fkEmpresa INT NOT NULL,
CONSTRAINT fkEmpresa FOREIGN KEY (fkEmpresa) REFERENCES empresa (idEmpresa),
nome VARCHAR(100) NOT NULL,
cargo VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
senha VARCHAR(100) NOT NULL
);

CREATE TABLE linha(
idLinha INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
fkEmpresa INT NOT NULL,
CONSTRAINT fkEmpresaLinha FOREIGN KEY (fkEmpresa) REFERENCES empresa (idEmpresa),
nome VARCHAR(100) NOT NULL,
numero INT NOT NULL
);

CREATE TABLE estação(
idEstacao INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
fkLinha INT NOT NULL,
CONSTRAINT fkLinha FOREIGN KEY (fkLinha) REFERENCES linha (idLinha),
nome VARCHAR(100)
);

CREATE TABLE Computador (
idComputador INT PRIMARY KEY AUTO_INCREMENT,
Hostname VARCHAR(50) NOT NULL,
Linha VARCHAR(50) NOT NULL,
Estacao VARCHAR(100) NOT NULL,
fkEmpresa INT NOT NULL,
	FOREIGN KEY (fkEmpresa) REFERENCES Empresa(idEmpresa)
);

CREATE TABLE Hardware (
idHardware INT PRIMARY KEY AUTO_INCREMENT,
SistemaOperacional VARCHAR(50) NOT NULL,
NomeCpu VARCHAR(255) NOT NULL,
Arquitetura VARCHAR(255) NOT NULL,
MemoriaEmUso VARCHAR(255) NOT NULL,
MemoriaTotal VARCHAR(255) NOT NULL,
SysAtividade VARCHAR(255)
);

INSERT INTO Hardware VALUES 
(null, 'Windows', '12th Gen Intel(R) Core(TM) i5-1235U', '16gb', '1TB', 'ON', null);

select * from empresa;

